#!/usr/bin/env python3
"""Keep the "Munich Sub-Districts (110)" Notion database in sync with the
district data in this repository.

Two sources of truth, one join key (`bt_nummer`, e.g. "09.1"):

  * Notion  -> ratings: the `Rating` (select, 0-5) and `Notes` columns,
               edited by hand. The script never overwrites them.
  * Repo    -> identity/geometry: `munich_bezirksteile_named.geojson`,
               regenerated by `fetch_districts.py`.

Behaviour:
  * First run (database does not exist yet): creates the database under the
    "Munich Districts Map" page and seeds all rows with `Rating` = 0
    (Explore).
  * One-time upgrade: if an existing database still has a numeric `Rating`
    column, it is converted in place to the `Rating` select (0-5).
  * Later runs: idempotent upsert keyed by `Code`. Metadata columns
    (Name, Borough, Area km², Centroid, Map) are refreshed; `Rating` and
    `Notes` are left alone, including for rows the user has already rated.

Requires the environment variable NOTION_TOKEN (an integration token).
Standard library only.
"""

import json
import os
import sys
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))

NOTION_VERSION = "2022-06-28"
NOTION_API = "https://api.notion.com/v1"
PARENT_PAGE_ID = "3b73e55d-d52c-8113-99bd-c0f1d0130a28"   # "Munich Districts Map"
NEW_DB_TITLE = "Munich Sub-Districts (110)"

GEOJSON = os.path.join(HERE, "munich_bezirksteile_named.geojson")

# Property name -> Notion type used when creating the database.
RATING_OPTIONS = [
    {"name": "0", "color": "gray"},
    {"name": "1", "color": "red"},
    {"name": "2", "color": "orange"},
    {"name": "3", "color": "yellow"},
    {"name": "4", "color": "green"},
    {"name": "5", "color": "green"},
]

SCHEMA = {
    "Name": {"title": {}},
    "Code": {"rich_text": {}},
    "Borough": {"rich_text": {}},
    "Rating": {"select": {"options": RATING_OPTIONS}},
    "Notes": {"rich_text": {}},
    "Area km²": {"number": {"format": "number"}},
    "Centroid Lat": {"number": {"format": "number"}},
    "Centroid Lng": {"number": {"format": "number"}},
    "Map": {"url": {}},
}


def token():
    t = os.environ.get("NOTION_TOKEN")
    if not t:
        sys.exit("NOTION_TOKEN is not set")
    return t


def api(method, path, body=None):
    req = urllib.request.Request(NOTION_API + path, method=method,
                                 data=json.dumps(body).encode() if body is not None else None,
                                 headers={"Authorization": "Bearer " + token(),
                                          "Notion-Version": NOTION_VERSION,
                                          "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def load_districts():
    with open(GEOJSON, encoding="utf-8") as fh:
        data = json.load(fh)
    rows = []
    for f in data["features"]:
        p = f["properties"]
        code = p["bt_nummer"]
        names = p.get("os_names") or []
        best = names[0] if names else None
        title = "%s (%s)" % (best, code) if best else "%s (unnamed)" % code
        lat, lng = p["centroid_lat"], p["centroid_lng"]
        rows.append({
            "code": code,
            "title": title,
            "borough": p.get("stadtbezirk_name") or "",
            "area_km2": round(p.get("flaeche_qm", 0) / 1e6, 2),
            "lat": lat,
            "lng": lng,
            "map_url": "https://www.google.com/maps?q=%.6f,%.6f&z=14" % (lat, lng),
        })
    rows.sort(key=lambda r: tuple(int(x) for x in r["code"].split(".")))
    return rows


def find_db():
    body = {"query": NEW_DB_TITLE,
            "filter": {"value": "database", "property": "object"}}
    res = api("POST", "/search", body)
    for obj in res.get("results", []):
        for t in obj.get("title", []):
            if t.get("plain_text") == NEW_DB_TITLE:
                return obj["id"]
    return None


def create_db():
    db = api("POST", "/databases", {
        "parent": {"type": "page_id", "page_id": PARENT_PAGE_ID},
        "title": [{"type": "text", "text": {"content": NEW_DB_TITLE}}],
        "properties": SCHEMA,
    })
    return db["id"]


def page_props(row, rating=None, notes=None):
    props = {
        "Name": {"title": [{"type": "text", "text": {"content": row["title"]}}]},
        "Code": {"rich_text": [{"type": "text", "text": {"content": row["code"]}}]},
        "Borough": {"rich_text": [{"type": "text", "text": {"content": row["borough"]}}]},
        "Area km²": {"number": row["area_km2"]},
        "Centroid Lat": {"number": row["lat"]},
        "Centroid Lng": {"number": row["lng"]},
        "Map": {"url": row["map_url"]},
    }
    if rating is not None:
        props["Rating"] = {"select": {"name": str(rating)}}
    if notes:
        props["Notes"] = {"rich_text": [{"type": "text", "text": {"content": notes}}]}
    return props


def existing_pages(db_id):
    """Map Code -> page id for all rows in the database."""
    out = {}
    cursor = None
    while True:
        body = {"page_size": 100}
        if cursor:
            body["start_cursor"] = cursor
        res = api("POST", "/databases/%s/query" % db_id, body)
        for page in res.get("results", []):
            code = page["properties"].get("Code", {}).get("rich_text") or []
            key = code[0]["plain_text"] if code else None
            if key:
                out[key] = page["id"]
        cursor = res.get("next_cursor")
        if not cursor:
            break
    return out


def migrate_db(db_id):
    """Upgrade an existing database where `Rating` is still a number to the
    `Rating` select (0-5). Idempotent: no-op once `Rating` is a select."""
    db = api("GET", "/databases/%s" % db_id)
    rating = db["properties"].get("Rating")
    if not rating or rating.get("type") == "select":
        return

    pages = {}
    cursor = None
    while True:
        body = {"page_size": 100}
        if cursor:
            body["start_cursor"] = cursor
        res = api("POST", "/databases/%s/query" % db_id, body)
        for page in res.get("results", []):
            code = page["properties"].get("Code", {}).get("rich_text") or []
            key = code[0]["plain_text"] if code else None
            num = page["properties"].get("Rating", {}).get("number")
            if key:
                pages[key] = (page["id"], int(num) if isinstance(num, (int, float)) else 0)
        cursor = res.get("next_cursor")
        if not cursor:
            break

    api("PATCH", "/databases/%s" % db_id,
        {"properties": {"RatingSel": {"select": {"options": RATING_OPTIONS}}}})
    for key, (page_id, rating) in pages.items():
        api("PATCH", "/pages/%s" % page_id,
            {"properties": {"RatingSel": {"select": {"name": str(rating)}}}})
    api("PATCH", "/databases/%s" % db_id, {"properties": {"Rating": None}})

    # Renaming to "Rating" can auto-suffix ("Rating 1") when the old name was
    # recently dropped; retry on whatever name the select property got.
    for _ in range(3):
        db = api("GET", "/databases/%s" % db_id)
        select_props = [name for name, p in db["properties"].items()
                        if p.get("type") == "select"]
        target = [n for n in select_props if n != "Rating"]
        if "Rating" in select_props or not target:
            break
        api("PATCH", "/databases/%s" % db_id,
            {"properties": {target[0]: {"name": "Rating"}}})
    print("Migrated Rating number -> select (%d rows)" % len(pages))


def sync():
    rows = load_districts()
    print("Loaded %d sub-districts from %s" % (len(rows), os.path.basename(GEOJSON)))

    db_id = find_db()
    if db_id is None:
        db_id = create_db()
        print("Created database %s -> %s" % (NEW_DB_TITLE, db_id))
        for row in rows:
            api("POST", "/pages", {
                "parent": {"database_id": db_id},
                "properties": page_props(row, rating=0),
            })
        print("Seeded %d rows" % len(rows))
    else:
        print("Database exists -> %s" % db_id)
        migrate_db(db_id)
        pages = existing_pages(db_id)
        created = updated = 0
        for row in rows:
            if row["code"] in pages:
                api("PATCH", "/pages/" + pages[row["code"]], {
                    "properties": page_props(row),
                })
                updated += 1
            else:
                api("POST", "/pages", {
                    "parent": {"database_id": db_id},
                    "properties": page_props(row, rating=0),
                })
                created += 1
        print("Updated %d, created %d (Rating/Notes left untouched)"
              % (updated, created))

    print("Sync done.")


if __name__ == "__main__":
    sync()
